FROM node:latest

ARG VERSION

RUN mkdir -p /app/NexxiotPush
RUN git clone --branch ${VERSION} https://github.com/YetAnotherGeorge/NexxiotPush.git /app/NexxiotPush
WORKDIR /app/NexxiotPush/PushClient

RUN npm install --global typescript
RUN npm install
RUN npm run build

CMD [ "npm", "run", "start" ]