FROM node:latest

ARG VERSION

RUN mkdir -p /app/PushClient
RUN git clone --branch ${VERSION} https://github.com/YetAnotherGeorge/NexxiotPush.git /app/PushClient
WORKDIR /app/PushClient

RUN npm install --global typescript
RUN npm install
RUN npm run build

CMD [ "npm", "run", "start" ]